services:
  - type: web
    name: parts-api
    env: python
    runtime: python3.12
    buildCommand: |
      pip install poetry
      poetry install --no-root
    startCommand: |
      poetry run alembic upgrade head
      poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parts-db
          property: connectionString
      - key: PORT
        value: 8000
      - key: SECRET_KEY
        sync: false

databases:
  - name: parts-db
    plan: free 